#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/PlugIns" ]; then
	PLUGINS_DIR="$TheSkyX_Path/PlugIns"
elif [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns64"
else
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns"
fi

echo "Installing in $PLUGINS_DIR/RotatorPlugIns/"

cp "/tmp/EsattoArco_X2/rotatorlist Arco.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/RotatorPlugIns/Arco.ui"
cp "/tmp/EsattoArco_X2/Arco.ui" "$PLUGINS_DIR/RotatorPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/RotatorPlugIns/PrimaLuceLab.png"
cp "/tmp/EsattoArco_X2/PrimaLuceLab.png" "$PLUGINS_DIR/RotatorPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/RotatorPlugIns/libArco.dylib"
cp "/tmp/EsattoArco_X2/libArco.dylib" "$PLUGINS_DIR/RotatorPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

echo "Installing in $PLUGINS_DIR/FocuserPlugIns/"

cp "/tmp/EsattoArco_X2/focuserlist Esatto.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/FocuserPlugIns/Esatto.ui"
cp "/tmp/EsattoArco_X2/Esatto.ui" "$PLUGINS_DIR/FocuserPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/FocuserPlugIns/PrimaLuceLab.png"
cp "/tmp/EsattoArco_X2/PrimaLuceLab.png" "$PLUGINS_DIR/FocuserPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/FocuserPlugIns/libEsatto.dylib"
cp "/tmp/EsattoArco_X2/libEsatto.dylib" "$PLUGINS_DIR/FocuserPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi


app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/rotatorlist Arco..txt"
	chown $app_owner "$PLUGINS_DIR/RotatorPlugIns/Arco.ui"
	chown $app_owner "$PLUGINS_DIR/RotatorPlugIns/PrimaLuceLab.png"
	chown $app_owner "$PLUGINS_DIR/RotatorPlugIns/libArcodylib"

	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/focuserlist Esatto.txt"
	chown $app_owner "$PLUGINS_DIR/FocuserPlugIns/Esatto.ui"
	chown $app_owner "$PLUGINS_DIR/FocuserPlugIns/PrimaLuceLab.png"
	chown $app_owner "$PLUGINS_DIR/FocuserPlugIns/libEsatto.dylib"
fi

rm -rf /tmp/EsattoArco_X2

